// exports.js
app.exportCSV = function(type){
    const data = this.getDataForType(type);
    if(!data.length) return;

    const headers = Object.keys(data[0]);
    const csv = [
        headers.join(","),
        ...data.map(row => headers.map(h => JSON.stringify(row[h] ?? "")).join(","))
    ].join("\n");

    const blob = new Blob([csv], { type:"text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${type}_export_${new Date().toISOString().slice(0,10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
};

app.exportInvoicePDF = function(invoiceId){
    const inv = this.getItemById("invoices", invoiceId);
    if(!inv){ alert("Invoice not found"); return; }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    doc.setFont("helvetica","bold");
    doc.setFontSize(18);
    doc.text("MyManager Invoice", 14, 18);

    doc.setFont("helvetica","normal");
    doc.setFontSize(12);

    const lines = [
        ["Invoice ID", String(inv.id)],
        ["Customer", inv.customerName],
        ["Amount", `$${Number(inv.amount).toFixed(2)}`],
        ["Date", inv.date],
        ["Status", inv.status],
    ];

    let y = 32;
    lines.forEach(([k,v])=>{
        doc.setFont("helvetica","bold");
        doc.text(k + ":", 14, y);
        doc.setFont("helvetica","normal");
        doc.text(String(v), 55, y);
        y += 10;
    });

    doc.setDrawColor(220);
    doc.line(14, y+4, 196, y+4);

    doc.setFont("helvetica","normal");
    doc.setFontSize(10);
    doc.text("Generated by MyManager Backoffice (VanillaJS)", 14, y+14);

    doc.save(`invoice_${inv.id}.pdf`);
};